# Generated by Django 3.2.18 on 2023-06-15 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publications', '0002_auto_20230612_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('description', models.TextField(null=True)),
                ('reviews_amount', models.IntegerField(default=0, null=True)),
                ('likes_amount', models.IntegerField(default=0, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='publications.publicationcategory')),
            ],
        ),
    ]
