export const PUBLICATION_CREATE_REQUEST = 'PUBLICATION_CREATE_REQUEST'
export const PUBLICATION_CREATE_SUCCESS = 'PUBLICATION_CREATE_SUCCESS'
export const PUBLICATION_CREATE_FAIL = 'PUBLICATION_CREATE_FAIL'
export const PUBLICATION_CREATE_RESET = 'PUBLICATION_CREATE_RESET'

export const PUBLICATION_UPDATE_REQUEST = 'PUBLICATION_UPDATE_REQUEST'
export const PUBLICATION_UPDATE_SUCCESS = 'PUBLICATION_UPDATE_SUCCESS'
export const PUBLICATION_UPDATE_FAIL = 'PUBLICATION_UPDATE_FAIL'
export const PUBLICATION_UPDATE_RESET = 'PUBLICATION_UPDATE_RESET'

export const PUBLICATION_DETAILS_REQUEST = 'PUBLICATION_DETAILS_REQUEST'
export const PUBLICATION_DETAILS_SUCCESS = 'PUBLICATION_DETAILS_SUCCESS'
export const PUBLICATION_DETAILS_FAIL = 'PUBLICATION_DETAILS_FAIL'
export const PUBLICATION_DETAILS_RESET = 'PUBLICATION_DETAILS_RESET'

export const PUBLICATIONS_FEED_REQUEST = 'PUBLICATIONS_FEED_REQUEST'
export const PUBLICATIONS_FEED_SUCCESS = 'PUBLICATIONS_FEED_SUCCESS'
export const PUBLICATIONS_FEED_FAIL = 'PUBLICATIONS_FEED_FAIL'

export const PUBLICATION_CREATE_REVIEW_REQUEST = 'PUBLICATION_CREATE_REVIEW_REQUEST'
export const PUBLICATION_CREATE_REVIEW_SUCCESS = 'PUBLICATION_CREATE_REVIEW_SUCCESS'
export const PUBLICATION_CREATE_REVIEW_FAIL = 'PUBLICATION_CREATE_REVIEW_FAIL'
export const PUBLICATION_CREATE_REVIEW_RESET = 'PUBLICATION_CREATE_REVIEW_RESET'
