export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'

export const USER_LOGOUT = 'USER_LOGOUT'

export const USERS_REQUEST = 'USERS_REQUEST'
export const USERS_SUCCESS = 'USERS_SUCCESS'
export const USERS_FAIL = 'USERS_FAIL'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST'
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS'
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL'

export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST'
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS'
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL'
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET'

export const ARTIST_PUBLICATIONS_REQUEST = 'ARTIST_PUBLICATIONS_REQUEST'
export const ARTIST_PUBLICATIONS_SUCCESS = 'ARTIST_PUBLICATIONS_SUCCESS'
export const ARTIST_PUBLICATIONS_FAIL = 'ARTIST_PUBLICATIONS_FAIL'

export const ARTIST_PRODUCTS_REQUEST = 'ARTIST_PRODUCTS_REQUEST'
export const ARTIST_PRODUCTS_SUCCESS = 'ARTIST_PRODUCTS_SUCCESS'
export const ARTIST_PRODUCTS_FAIL = 'ARTIST_PRODUCTS_FAIL'

export const ARTIST_DETAILS_REQUEST = 'ARTIST_DETAILS_REQUEST'
export const ARTIST_DETAILS_SUCCESS = 'ARTIST_DETAILS_SUCCESS'
export const ARTIST_DETAILS_FAIL = 'ARTIST_DETAILS_FAIL'

export const ANOTHER_ARTIST_DETAILS_REQUEST = 'ANOTHER_ARTIST_DETAILS_REQUEST'
export const ANOTHER_ARTIST_DETAILS_SUCCESS = 'ANOTHER_ARTIST_DETAILS_SUCCESS'
export const ANOTHER_ARTIST_DETAILS_FAIL = 'ANOTHER_ARTIST_DETAILS_FAIL'

export const ARTIST_UPDATE_DETAILS_REQUEST = 'ARTIST_UPDATE_DETAILS_REQUEST'
export const ARTIST_UPDATE_DETAILS_SUCCESS = 'ARTIST_UPDATE_DETAILS_SUCCESS'
export const ARTIST_UPDATE_DETAILS_FAIL = 'ARTIST_UPDATE_DETAILS_FAIL'
export const ARTIST_UPDATE_DETAILS_RESET = 'ARTIST_UPDATE_DETAILS_RESET'

export const ARTIST_FOLLOW_REQUEST = 'ARTIST_FOLLOW_REQUEST'
export const ARTIST_FOLLOW_SUCCESS = 'ARTIST_FOLLOW_SUCCESS'
export const ARTIST_FOLLOW_FAIL = 'ARTIST_FOLLOW_FAIL'

export const ARTIST_UNFOLLOW_REQUEST = 'ARTIST_UNFOLLOW_REQUEST'
export const ARTIST_UNFOLLOW_SUCCESS = 'ARTIST_UNFOLLOW_SUCCESS'
export const ARTIST_UNFOLLOW_FAIL = 'ARTIST_UNFOLLOW_FAIL'

export const ARTIST_FOLLOWERS_REQUEST = 'ARTIST_FOLLOWERS_REQUEST'
export const ARTIST_FOLLOWERS_SUCCESS = 'ARTIST_FOLLOWERS_SUCCESS'
export const ARTIST_FOLLOWERS_FAIL = 'ARTIST_FOLLOWERS_FAIL'

export const ARTIST_FOLLOWING_REQUEST = 'ARTIST_FOLLOWING_REQUEST'
export const ARTIST_FOLLOWING_SUCCESS = 'ARTIST_FOLLOWING_SUCCESS'
export const ARTIST_FOLLOWING_FAIL = 'ARTIST_FOLLOWING_FAIL'
