# Generated by Django 3.2.18 on 2023-06-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_alter_artist_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='username',
            field=models.CharField(default=None, max_length=20, unique=True),
        ),
    ]
