# Generated by Django 3.2.18 on 2023-06-12 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_alter_artist_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='artist',
            managers=[
            ],
        ),
    ]
