# Generated by Django 3.2.18 on 2023-06-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0004_alter_artist_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
