# Generated by Django 3.2.18 on 2023-06-13 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0008_auto_20230613_1322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={},
        ),
        migrations.RemoveField(
            model_name='artist',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='is_staff',
        ),
    ]
