# Generated by Django 3.2.18 on 2023-06-12 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='user',
            new_name='artist',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='artist',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='user',
            new_name='artist',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='artist',
        ),
    ]
