# Generated by Django 3.2.18 on 2023-06-20 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_auto_20230619_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderaddress',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='publication',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderAddress',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
